# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Michael Barbour, PhD
tagline:         'Personal Website'
description:     'Senior Research Scientist' 
work:             'University of Washington <br>Dept of Mech Engineering'

url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mike Barbour'
  url:            

gems: 		[jekyll-paginate]

paginate:         5

paginate_path:   "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
